# Enviroment
ENV = 'local'
# Exchanges
UPBIT = 'Upbit'
BINANCE = 'Binance'
# All Exchanges
EXCHANGE_LIST = [UPBIT, BINANCE]
# WEBSOCKET
SOCKET_PING_INTERVAL = 20 # 20초
SOCKET_RETRY_TIME = 30 # 30초
SOCKET_PING_TIMEOUT = 30 # 30초

# TELEGRAM
TELEGRAM_BOT_TOKEN = "6690231866:AAEUWgkWPaML-tx8VplLo4BPE9tabyq-9i8"
TELEGRAM_MESSAGE_MAX_SIZE = 4095

# DELAY
DOLLAR_UPDATE = 5 * 60 # 달러가격 업데이트 주기, 1시간
SOCKET_ORDERBOOK_DELAY = 30
COMPARE_PRICE_START_DELAY = 2 * 60
COMPARE_PRICE_DELAY = 10 # 가격비교 최초 실행대기, 5분
CHECK_ORDERBOOK_START_DELAY = 2 * 60 # 호가창 계산 실행대기
TIME_DIFF_CHECK_DELAY = 30 * 60 # 바이낸스 서버와 시간비교 주기, 30분
ORDERBOOK_SIZE = 6 # 호가 상하방 몇틱 저장할 지 지정

# MEASURE
MEASURE_OPEN_COUNT = 2
MEASURE_OPEN_GAP = 0.33
MEASURE_CLOSE_GAP = 1.5
OPEN_INSTALLMENT = 0.33
MEASURE_STOP_LOSS = 4
CURR_OPEN_CLOSE_GAP = 0.3
FRONT_GAP = 10

# ETC
MILLION = 100000000 # 억
BALANCE = 10000000 # 천만원
UPBIT_FEE = 0.0005
BINANCE_FEE = 0.0004
NOTI_GAP_STANDARD = 0.1 # TODO 거래소간 차이가 발생할 때 알림을 보낼 기준(%) 개인별로 설정
